### ISSUE TITLE
Undefined Mat Conversion Issue

### ISSUE THREAD

**Issue by agjaeger** [bk5115545/camera_array_multitouch_cpp#1]
Successful build but on run the program breaks and crashes due to a Frame to Mat Conversion

Call Stack Upon Breaking:
- cv::Mat::Mat(const cv::Mat & m) Line 115
- Frame::operator cv::Mat() Line 29
- main(char \* argsv, char argc) Line 56

**Comment by bk5115545** [comment]
I wish I could scream curse words at this programming language.
