### ISSUE TITLE
Turn a table top to multitouch surface

### ISSUE THREAD

**Issue by Scherady** [bk5115545/camera_array_multitouch_cpp#16]
Hi,

Would it be possible to use your camera array system on a table to detect in real time simultaneous taps of up to 10 fingers and provide (x, y) coordinates of tap positions on the table?

Thank you.

**Comment by bk5115545** [comment]
While the end goal is to provide (x,y)'s for each touch, we're not very close and this project isn't in active development as resources have been reallocated at our place of employment.

Also, 10 simultaneous touches would require quite a few cameras (16+) and thus require a lot of processing power.  I'm not sure that it is a reasonable goal when using cameras.  Now if you were to use some kind of laser grid with oscillating interlaces then I think it would be possible (but a lot more expensive).
