### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by bk5115545** [bk5115545/camera_array_multitouch_cpp#2]
Ok so it's time to actually manage memory.
There are several **::TODO::** and a **TODO** which have things to do about freeing memory.  Right now opencv whines when the usable addresses pass 4GB which is an issue if we want to deploy on a Raspberry PI (4GB) of ram.

Need to:
- Free closed threads in **Transformer.cpp**
- Free processed frames in **Transformer.cpp**
- Free collected results in **main**

---

And there might be something else to free too...

**Comment by agjaeger** [comment]
Unfortunately, we will need to be more careful as the Raspberry PI only supports 1GB max (as of February 2015). Though we can find more luxurious alternatives.

**Comment by bk5115545** [comment]
Most of the memory issues are closed however we still leak 8 bytes every main loop iteration.  We also leak 74 bytes every thread instantiation.

I need to look at these more.

Commit 992cbadb9733da78d779280c1db7b7c8df08a8e3 lowered memory usage by more than 800MB.

**Comment by bk5115545** [comment]
All known memory leaks were closed with commit bc26035574714d4235b42d51e8aba4dc15bb294a.  We still have to watch out for a growing queue size in the thread pool job queue but that's another issue entirely.
