### ISSUE TITLE
CameraDevice::decodeFrame Channels

### ISSUE THREAD

**Issue by agjaeger** [bk5115545/camera_array_multitouch_cpp#3]
When called, capture.retrieve puts data into the mat and then converts it into a new frame, however when channel is greater than 0, it is possible that the extra dimensions will not fit into the frame and therefore produce bugs.

To fix we need to wait until more sophisticated cameras are implemented and then test with the correct channel numbers. Webcams should not be affected by this bug.

**Comment by bk5115545** [comment]
This won't be a problem because the Frame object takes a reference to a cv::Mat and stores a copy locally.  Any number of channels that is supported by cv::Mat is supported by Frame.
