### ISSUE TITLE
Camera ID - Locked Processors

### ISSUE THREAD

**Issue by agjaeger** [bk5115545/camera_array_multitouch_cpp#9]
We need to consistently dispatch certain frames to certain buffers. The frames get jumbled on exit from the processors. It looks like a fix in Transformer.cpp is needed to ensure the frames and cameras

The issue can be duplicated via commit 7fd2a64e291d0b59e82a0ef98f5578e458d54025. When running the program notice the background being subtracted and sent to various cameras.

**Comment by bk5115545** [comment]
This is no longer an issue with the new Transformer and the new FrameCache objects.
